Document: angora
Title: Debian angora Manual
Author: <insert document author here>
Abstract: This manual describes what angora is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/angora/angora.sgml.gz

Format: postscript
Files: /usr/share/doc/angora/angora.ps.gz

Format: text
Files: /usr/share/doc/angora/angora.text.gz

Format: HTML
Index: /usr/share/doc/angora/html/index.html
Files: /usr/share/doc/angora/html/*.html
